# Generated by Django 4.2.2 on 2023-06-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='numero',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
