# Generated by Django 4.2.2 on 2023-06-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_local_options_compromisso_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
