# Generated by Django 4.2.2 on 2023-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_anotacao_compromisso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacao_compromisso',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
    ]
