# Generated by Django 4.2.2 on 2023-06-23 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0009_alter_anotacao_compromisso_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotacao_compromisso',
            options={'verbose_name_plural': 'Anotações nos Compromissos'},
        ),
        migrations.AlterField(
            model_name='anotacao_compromisso',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
