# Generated by Django 4.2.2 on 2023-06-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_compromisso_registro_alter_local_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convidado',
            options={'verbose_name_plural': 'Convidados'},
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Local', to='agenda.local'),
        ),
    ]
