# Generated by Django 4.2.2 on 2023-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_alter_convidado_options_alter_compromisso_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='Convidados',
            field=models.ManyToManyField(related_name='Convidados', to='agenda.convidado'),
        ),
    ]
