# Generated by Django 4.2.2 on 2023-07-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_alter_compromisso_convidados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compromisso',
            options={'verbose_name_plural': 'Compromissos'},
        ),
    ]
