# Generated by Django 4.2.2 on 2023-07-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_alter_compromisso_options_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
